sudo: false
language: node_js
node_js:
  - 9
  - 8
  - 7
  - 6
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn install
script:
  - yarn validate
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master